version: "3.8"

services:
  nextjs-azenox-fr:
    build: .
    container_name: nextjs-azenox-fr
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - proxy

networks:
  proxy:
    external: true